import { supabase } from "@/integrations/supabase/client";

interface LeadUpdate {
  email: string;
  sales_status: string | null;
  sales_rep: string | null;
  kwaliteit: string | null;
  toelichting: string | null;
  sales_comment: string | null;
}

export const processLeadUpdates = async () => {
  // Helper function to normalize quality values
  const normalizeKwaliteit = (value: string | null): string | null => {
    if (!value) return null;
    const normalized = value.toLowerCase().trim();
    if (normalized === "slecht") return "Slecht";
    if (normalized === "goed") return "Goed";
    if (normalized === "redelijk") return "Redelijk";
    if (normalized.includes("goed") && normalized.includes("klant")) return "Goed - klant";
    return null;
  };

  // Helper function to normalize sales status values
  const normalizeSalesStatus = (value: string | null): string | null => {
    if (!value) return null;
    const normalized = value.trim().toLowerCase();
    
    // Normalize to consistent capitalization
    if (normalized === "te contacteren") return "Te contacteren";
    if (normalized === "gecontacteerd") return "Gecontacteerd";
    if (normalized === "niet relevant") return "Niet relevant";
    if (normalized === "afgewezen") return "Afgewezen";
    if (normalized === "gesprek gepland") return "Gesprek gepland";
    if (normalized === "fysiek") return "fysiek";
    
    // Return trimmed value if no match
    return value.trim();
  };

  // Helper function to normalize sales rep values
  const normalizeSalesRep = (value: string | null): string | null => {
    if (!value) return null;
    const normalized = value.trim();
    // Keep Michaël and Michael separate
    // Only normalize obvious typos or case variations
    if (normalized.toLowerCase() === "jpierre") {
      return "JPierre";
    }
    if (normalized === "michael") {
      return "Michael";
    }
    if (normalized === "michäel") {
      return "Michäel";
    }
    // Return as-is for others (Dominique, Alexander)
    return normalized;
  };

  // Data from the spreadsheet - mapping columns correctly
  const rawUpdates = [
    { email: "tahirilina809@gmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "morkosnixo@gmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "atelier43.wood@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed", toelichting: "kleine zelfstandige keukenbouwer" },
    { email: "team@yvebe.be", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: "Mooie keukenwinkel" },
    { email: "lepoutre.pauline@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architecte" },
    { email: "lize.dekeersmaeker@outlook.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Architect" },
    { email: "steven@noitzgroup.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "contact genomen" },
    { email: "info@maano.be", sales_status: "Te contacteren", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Meubels op maat" },
    { email: "glenn@construmax.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "aannemingsbedrijf badkamers - keukens" },
    { email: "philippe@onki.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Contact genomen" },
    { email: "gregory@meublis.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "contact genomen" },
    { email: "b.b.renovatie@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Vooral tegelwerken." },
    { email: "jenno.adriaenssens@icloud.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed - Klant", toelichting: "Schrijnwerkerij interieur" },
    { email: "info@ateliernerf.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Meubelmaker" },
    { email: "teirlynck.alexandra@orange.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "contacté particulier" },
    { email: "teirlynck.alexandra.1985@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "contacté particulier" },
    { email: "jos@jedeka.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "keukenwinkel" },
    { email: "romain_1985@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "jeugdzorginstelling" },
    { email: "interieurwerken@jwconstruct.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: null },
    { email: "piquetp02@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "verkleedwinkel" },
    { email: "piquetpat02@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "contacté particulier" },
    { email: "info@schrijnwerken-quidousse.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Schrijnwerken Quidousse - Kevin Quidousse" },
    { email: "info@egsjikinterieur.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Interieurbouwer" },
    { email: "info@gunternijns.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed", toelichting: "Doet in keukens" },
    { email: "decat.christophe@outlook.com", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "schrijnwerker" },
    { email: "j.luyks@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: null },
    { email: "info@pastijnbo.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "keukenbouwer" },
    { email: "lien@detai.be", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "interieurontwerp" },
    { email: "glenn@dvbouwcoordinatie.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "aannemer plaatst zelf de keukens in de bouwprojecten" },
    { email: "design@evelinetytgat.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: null },
    { email: "info@bdinterieurstyling.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: null },
    { email: "andyflament140@hotmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "Schrijnwerker Zonnebeke | AF Wood Concept: ramen, keukens, gyprocwerken" },
    { email: "klaas@pastijnbo.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "keukenbouwer" },
    { email: "kristofma@hotmail.com", sales_status: "Te contacteren", sales_rep: "Michael", kwaliteit: "goed", toelichting: "architect" },
    { email: "info@braeckmansmaatwerk.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed - Klant", toelichting: "Afspraak op 03/09" },
    { email: "jonas@artifexinterior.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed - Klant", toelichting: "Klant bij ons" },
    { email: "info@dekeuken-prins.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed - Klant", toelichting: "Klant" },
    { email: "info@uni-build.be", sales_status: "Gecontacteerd", sales_rep: "Michäel", kwaliteit: "redelijk", toelichting: "Voegwerken" },
    { email: "sammy.jespers@gmail.com", sales_status: "Te contacteren", sales_rep: "Michael", kwaliteit: "redelijk", toelichting: "Interieurwerker" },
    { email: "jodi_cartuyvels@hotmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "redelijk", toelichting: "Heeft nog niet" },
    { email: "info@exactinterior.com", sales_status: "Gesprek gepland", sales_rep: "Michael", kwaliteit: "redelijk", toelichting: "Is bellen om te horen wat voor bedrijf het is" },
    { email: "fred@koroway.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "samvl26@icloud.com", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "bellen" },
    { email: "steven@atelier29.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurinrichting, schilderwerken, geen keukens" },
    { email: "info@hd-interiors.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurinrichting, plaatst maar af en toe een keuken" },
    { email: "charlotte.fockedey@gmail.com", sales_status: "Afgewezen", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "werkt voor architectenbureau" },
    { email: "info@renovatie-huis.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "renovatiewerken?" },
    { email: "comptegaming16@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "vercaigne.laurent@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "is bellen om te horen voor wat ze keramiek nodig hebben" },
    { email: "cools.johan.temse@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurinrichting, plaatst maar af en toe een keuken" },
    { email: "minguetdo@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "Renovatie en decoratie bedrijf" },
    { email: "contact@davidbovyarchitecture.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: null },
    { email: "jeromeschmitz.architecte@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architectenbureau" },
    { email: "info@cuisines-mailleux.be", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: "keukenwinkel" },
    { email: "lubriceda@hotmail.frl", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: null },
    { email: "ledi_entreprise@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "admin@opusdesign.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "Meubelbedrijf Accueil | Opus Design" },
    { email: "shift.architecture@skynet.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architectenbureau" },
    { email: "Venkensabrina@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: null },
    { email: "fraipont.benjamin@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: null },
    { email: "pillonmarco1983@hotmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: null },
    { email: "francoise-gerard@hotmail.com", sales_status: "Gecontacteerd", sales_rep: "dominique", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "guedesmaderolivier@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "styled@outlook.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "Is bellen om te horen wat ze juist doen" },
    { email: "zaina.b@menuiseriesac.be", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed", toelichting: "houtbewerking, composiet" },
    { email: "cedric.hoffelt@hotmail.com", sales_status: "Gecontacteerd", sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: "keukenwinkel" },
    { email: "vincentleclercq1983@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architecte" },
    { email: "philippedebloos@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "particulier of timmerman" },
    { email: "laurent@hep-design.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architectenbureau" },
    { email: "Sabrinapasteger2@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "scene10@skynet.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "architectenbureau" },
    { email: "christelle.girardot@outlook.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "contact@ardenecorenov.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "a recontacter" },
    { email: "info.woodedgedesign@gmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurbouwer, gebruikt nog geen keramiek maa ziet wel mogelijkheden" },
    { email: "tegellux@proximus.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "maatwerk sanitair, mogelijkheden bekijken." },
    { email: "desaerjonas@hotmail.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurschrijnwerker" },
    { email: "info@maximedhondt.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurarchitecte, interesse in keramische materialen" },
    { email: "Delmotte@Mat-co.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "is bellen" },
    { email: "info@int-hout.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "interieurbouwer," },
    { email: "an-peeters@telenet.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: "interieurinrichting, schilderwerken, geen keukens" },
    { email: "fl.schelfhout@gmail.com", sales_status: null, sales_rep: "Michael", kwaliteit: "redelijk", toelichting: null },
    { email: "nika.gordts@sensedesign.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Dakdekker" },
    { email: "diego@cucu.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Audiovisuele bedrijf" },
    { email: "neal.stegmann@hotmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Covarte" },
    { email: "kst.bvba@telenet.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Transportbedrijf" },
    { email: "pascar.ioana@yahoo.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Particulier" },
    { email: "olivier@studiofromm.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Niks met keukens te maken" },
    { email: "tomdeloose@hotmail.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Loodgieter" },
    { email: "businessglolocally@gmail.com", sales_status: "Niet relevant", sales_rep: "michael", kwaliteit: "slecht", toelichting: "Niks met interieur te maken" },
    { email: "dorothee.decoratie@icloud.com", sales_status: "Niet relevant", sales_rep: "michael", kwaliteit: "slecht", toelichting: "Raamdecoratie" },
    { email: "evelienvanbrabant86@hotmail.com", sales_status: "Gecontacteerd", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Is niet rechtstreeks via deze bureau" },
    { email: "jacqueline.ruisi@live.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Verkoop van verlichting" },
    { email: "gilles.hendrickx1@gmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "IT" },
    { email: "dagummy@gmail.com", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: null },
    { email: "info@mgmt-bs.be", sales_status: "Niet relevant", sales_rep: "michael", kwaliteit: "slecht", toelichting: "particulier denk ik + it bedrijf" },
    { email: "sita.langenaeken@gmail.com", sales_status: null, sales_rep: "Michael", kwaliteit: "slecht", toelichting: null },
    { email: "inge.vanoirbeek@telenet.be", sales_status: null, sales_rep: "Michael", kwaliteit: "slecht", toelichting: null },
    { email: "info@fugaziprojects.be", sales_status: "Afgewezen", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Renovatie bedrijf" },
    { email: "bert@whatsnxt.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "karendevroe@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "marketingbureau" },
    { email: "amber.deprez99@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "hello@studiobalearic.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "verkoopt interieurspullen, geen uitvoering of ontwerp" },
    { email: "icm.interieur@gmail.com", sales_status: "Te contacteren", sales_rep: "Michael", kwaliteit: "slecht", toelichting: null },
    { email: "david.wielfaert@telenet.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "laurentviaene@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "binoche2009@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "dc_ceram@hotmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "sud de la france carreleur" },
    { email: "philippengbr@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "cbabou1@hotmail.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "is bellen, in de buurt van Nantes" },
    { email: "mag.laot@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "p.abaza@googlemail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "melanmichez@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "m.farazandehmehr@avantpropos.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: null },
    { email: "quentinilyane@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "nikokardia@hotmail.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier" },
    { email: "contact@andara-agencement.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "contacté envoi digital" },
    { email: "sebastien@piastrella-carrelage.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "contacté et visité" },
    { email: "elena.delbassez@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "contact@tinerbos.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "interieurwinkel" },
    { email: "mariechristine.despriet@sfr.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "adeline.1989@hotmail.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier" },
    { email: "k.jozwiak@outlook.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "Particulier" },
    { email: "lambertemeline3@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "Kinderdagverblijf" },
    { email: "vincent.senechal460@orange.fr", sales_status: "Te contacteren", sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "Akuzmychy@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "aconcept10@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "architect" },
    { email: "jeanfrancois.morant@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "noemie.telliez@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "fotograaf" },
    { email: "stefcatry@aol.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "bacheletmelanie@yahoo.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "titinehego0@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "achats@global-market.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "raynald59@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "houyou@gmx.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "lesotamelie77@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "n.loiselle@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "ambrecevaux1@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "sofiamafalda2@hotmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "m***c@gmail", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "ludivine-dressing@hotmail.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "rd-menuiserie@sfr.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "téléphoner" },
    { email: "swinfan@hotmail.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "bruno.martin717@orange.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "deraveanneseverine@yahoo.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "loubrylouna@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "kaaswinkel" },
    { email: "sabrina6211462290@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "marionvasse16@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "zit in het leger" },
    { email: "bishop62370@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "Amerikaanse folklore club" },
    { email: "juliecrmpn@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "decorateur" },
    { email: "rexora.3@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "machukaina@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "studenten" },
    { email: "e.justmoi@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "carbonnet19@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "schoonheidssalon" },
    { email: "fred.berteloot@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "rinderlearmand@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "AR Productions - Agence de productions audiovisuelles en Aveyron" },
    { email: "sylvaingouffier@gmail.com", sales_status: "Te contacteren", sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "thieulep@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "sabinelemasson76@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "vidalisabelle2012@hotmail.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "contact@atelier-19.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "architectenbureau" },
    { email: "linda801@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "natacha.delobelle@orange.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "colnot.quentin@yahoo.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "kunstenaar" },
    { email: "bruxellesandra@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "laborant" },
    { email: "esrakiymazz@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "lilalydiaelsa@icloud.com", sales_status: "fysiek", sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "Praktijk mentale welzijn" },
    { email: "penitotaurore827@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "cordierorlane7@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "leerkracht" },
    { email: "crc.lakwerken@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "lakwerken, niets met keukens te maken" },
    { email: "maureengeldhof@hotmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier" },
    { email: "dvanheck.dvh@gmail.com", sales_status: "Gecontacteerd", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier" },
    { email: "didier.reyns@comobo.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed", toelichting: "Comobo, cuisines et menuiseries sur-mesure à Jumet." },
    { email: "diacarlito@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "keukenwinkel" },
    { email: "contact@waoo-home.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "goed", toelichting: "interieurarchitect" },
    { email: "cuisines@batyhome.be", sales_status: "Gecontacteerd", sales_rep: "Michael", kwaliteit: "goed - Klant", toelichting: "MHK lid + Bezoeken BatyHome – Votre expert en salle de bains, chassis et meuble sur mesure" },
    { email: "sanderghesquiere@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "denis.vanboterdal@mons.mobalpa.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: "klant" },
    { email: "info@cuisitop.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: null },
    { email: "jonathan.warnier@skynet.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: null },
    { email: "gaetean@cubeconstruct.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "goed - Klant", toelichting: null },
    { email: "info@guidosse.com", sales_status: "Afgewezen", sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "werfleider" },
    { email: "joke.vrijens@didiom.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "marketeer" },
    { email: "xammax32@hotmail.com", sales_status: "Niet relevant", sales_rep: "Michael", kwaliteit: "slecht", toelichting: "pastaman?" },
    { email: "chvanreeth@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: null },
    { email: "info@dcmenuiserie.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "téléphoner" },
    { email: "marie@bonten.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "Aannemingsbedrijf renovatiewerken" },
    { email: "ingrid.franssens@telenet.be", sales_status: "Niet relevant", sales_rep: "Michäel", kwaliteit: "slecht", toelichting: "Bedrijf met slechte cijfers en website werkt ook niet meer." },
    { email: "katrien.filiep.overslag@gnail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "bvoneche@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "architectenbureau" },
    { email: "ccracing500@gmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "redelijk", toelichting: "téléphoner" },
    { email: "nicophanie@aliceadsl.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "Architecte d'intérieur – Commune de Wahagnies" },
    { email: "Contact@andara-agencement.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "redelijk", toelichting: "Interieurarhitectenbureau Lambersart Frankrijk" },
    { email: "gaetan.ackermans@hotmail.com", sales_status: "Afgewezen", sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "leadegobert@gmail.com", sales_status: "Afgewezen", sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "brigittepalmiero@gmail.com", sales_status: "Afgewezen", sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "immokantoor" },
    { email: "guy.neyt1@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "cds0659@gmail.com", sales_status: "Niet relevant", sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "?" },
    { email: "Fockaertvalerie@hotmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "niets terug te vinden" },
    { email: "info@tombuysse.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "Fotograaf die voor ons werkt" },
    { email: "cc@coeck.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "pietrosam8@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "?" },
    { email: "ann.vanderheeren@skynet.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "volbrecht.lynn@telenet.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "psychoterapeute" },
    { email: "bekaert.maarten@hotmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "nelegoethals@aol.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "stevenorshy@hotmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "pascal.dumez@telenet.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "snoecksuzy@icloud.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier, werkt in een vleesbedrijf" },
    { email: "marijke1102@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "particulier" },
    { email: "sofie.verb@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "geen info, adres, tel nummer, bedrijf" },
    { email: "bart.van.vlierberghe@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "geen info, geen correct tel nummer" },
    { email: "dummypriem@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "hilde.work.smarter@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "bladeoffury@gmail.com", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "yvan.decupere@skynet.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: "it bedrijf" },
    { email: "ward.claus@telenet.be", sales_status: "Niet relevant", sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "jos@ocmw.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "klaeremans@gmail.com", sales_status: null, sales_rep: "Michael", kwaliteit: "slecht", toelichting: null },
    { email: "niels@alkar.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "COLBLOC" },
    { email: "lizebroekx@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "tandengroef@outlook.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "kathleenemieke@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "jasmien.ubben@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "d.concept@live.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "multimediabedrijf" },
    { email: "mohamedaminben@icloud.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "advocaten" },
    { email: "francois@kubup.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "standen in karton zoal linkon of tuinhuizen" },
    { email: "Malika.ben.abid@dovy.be", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "wij hebben hun folder ook gedownload over trends" },
    { email: "debrjacky@hotmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "de club voor edelstenen" },
    { email: "shambuyipeter@yahoo.fr", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: "elektricien" },
    { email: "profco62@laposte.net", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "decosterlauryne@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "silva.mont@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "klein renovatiebedrijf isolatie en bepleistering" },
    { email: "fredericlyp@orange.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "ontwerper" },
    { email: "christine.courbot@laposte.net", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "juliebarbieux0@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "Étudiante décoration d'intérieur" },
    { email: "chtiigui62@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "?" },
    { email: "emeline.carette@yahoo.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "matdompom@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "aurianned@hotmail.com", sales_status: null, sales_rep: "Dominique", kwaliteit: "slecht", toelichting: null },
    { email: "defoortjulien@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "ncanler@orange.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "creaflore2@wanadoo.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "annabelle.denis.luchez@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "axlroses1999@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "mounine.hd@gmail.com", sales_status: null, sales_rep: "Michael", kwaliteit: "slecht", toelichting: "?" },
    { email: "francoise.stevenart@laposte.netf", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "?" },
    { email: "famille.labadie59@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "marchanderic91@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "p.margin@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "particulier denk ik" },
    { email: "li.cathy@neuf.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "julienparsa@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "laurentdebacker91@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "eri-ls@hotmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "particulier" },
    { email: "pablito59@hotmail.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "it firma" },
    { email: "sasbroneg@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "niks over te vinden" },
    { email: "bernardgauthier91@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "is iets in de bouw, zeer weinig omzet onbetrouwbaar" },
    { email: "geoffrey.herbin@flutech-industrie.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "lasser" },
    { email: "dutrieux.cyril@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "landbouwer" },
    { email: "kirsteinanthony@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "immokantoor" },
    { email: "amdconsult60@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "niet veel over te vinden" },
    { email: "baptiste.degr@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "BD Agencements - L'art de la menuiserie et de l'agencement depuis 35 ans" },
    { email: "denis'garinsf'r@gmail.com", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: null },
    { email: "agar.robin@wanadoo.fr", sales_status: null, sales_rep: "JPierre", kwaliteit: "slecht", toelichting: "?" },
    { email: "marinelse.business@outlook.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "supplies@acelectronics.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "electro handel" },
    { email: "sbpacorse@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "?" },
    { email: "jeanmariehardy1964@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "helene.flygare@outlook.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "jensparthoensinterieur@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "katrien@fraam.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "julie.cardon@hotmail.be", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "goed", toelichting: null },
    { email: "yannick.schumers@houbennv.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "COLBLOC" },
    { email: "jeroen.brughmans@dbv-architecten.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "espritparisienne@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "delmotte@mat-co.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "MATco Gavere - schrijnwerk | schilderwerken | maatmeubilair" },
    { email: "jordi.biebaut@outlook.com", sales_status: null, sales_rep: null, kwaliteit: "redelijk", toelichting: "Home - Wood Edge Design" },
    { email: "Nico@nicofoubert.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "dorien.vermeulen30@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "verpro@outlook.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "schrijnwerkerij" },
    { email: "Sam@craftedstudio.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "hello@studioverseau.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@freprojects.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "vanweertinterieurbouw@telenet.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "Van Weert Interieurbouw - Berlaar | Keukens - Badkamers - Dressings - Binnendeuren - Parket - Laminaat - Algemene schrijnwerkerij - Totaalprojecten - Gyprocwerken - Maatmeubilair" },
    { email: "info@vlassakarchitects.be", sales_status: null, sales_rep: "Michael", kwaliteit: "redelijk", toelichting: "ik zou ze wel stalen opsturen" },
    { email: "niels@ateljeep.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "knokke@qsine.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "Qsine - The fine art of kitchen architecture in Antwerpen and Knokke" },
    { email: "info@mprojectsbv.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "dens.braeken@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "serge.truyens@telenet.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "lindevandecaveye@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "bjorn.vanalderwerelt@telenet.be", sales_status: "Afgewezen", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "nearly.newhome@outlook.com", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "goed", toelichting: null },
    { email: "deneefmanon@gmail.com", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: null },
    { email: "patrick.vanbuel@virusfree.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "wimvanhees@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "stef.lodewyckx@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "stijn.detemmerman@hotmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "redelijk", toelichting: null },
    { email: "guustgoussaert@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "frederik.duyck@outlook.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "maatwerk interieur, keuken" },
    { email: "truyensserge1971@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "hello@stephaniamilazzo.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: null },
    { email: "annelies.lavreysen@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@trustwolf.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "renovaties" },
    { email: "eline@fraam.be", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "jolijn@ateliersosu.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@fermmaatwerk.be", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "schrijnwerker/keukens" },
    { email: "fienwarnez@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "coiffeur" },
    { email: "geoffrey@eventus-interieur.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "Eventus Interieur - uw schrijnwerker van dienst." },
    { email: "wouters.as@telenet.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: "Algemene schrijnwerkerij - Alg. schrijnwerkerij Wouters" },
    { email: "mydesignmehmet@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "samcotecbv@hotmail.com", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "clea.silvia05@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@kwast-schilderwerken.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "schilder" },
    { email: "sebastien.castelein@orange.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "arno@vabouw.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "laura.de.waele3@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "school" },
    { email: "test@stretchinnovation.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "inedingenen@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "test@fb.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "frederik.vangansen@protonmail.com", sales_status: "Gecontacteerd", sales_rep: "Alexander", kwaliteit: "goed", toelichting: "interieurbouwer" },
    { email: "lynn.vanpuyvelde@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "MQL, architect https://sparklynn.be/contact" },
    { email: "Info@kwast-schilderwerken.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "schilder" },
    { email: "info@stronk-interieur.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "MQL, architect" },
    { email: "cadetangelique@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@atelierredefine.be", sales_status: "Te contacteren", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "MqL Startpagina - Interieur Design Denderhoutem | Atelier Redefine" },
    { email: "j.mkn2407@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "morgane.vandevelde1@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "Info@diegodemeyer.be", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: "electrozaak" },
    { email: "elke.vanhalst.2000@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "lagaethierry@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "pe.thoelen@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "info@maximrotsaert.be", sales_status: "Te contacteren", sales_rep: null, kwaliteit: "redelijk", toelichting: null },
    { email: "miekevanpamel@hotmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "pieterhuybrechts@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "goethalsjessy@gmail.com", sales_status: "Niet relevant", sales_rep: "Alexander", kwaliteit: "slecht", toelichting: null },
    { email: "babs.doms@outlook.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "MQL" },
    { email: "stien2801@hotmail.be", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "MQL" },
    { email: "rosemarie.vanbaelen@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: "mQL" },
    { email: "info@db-schrijnwerken.be", sales_status: null, sales_rep: "Michael", kwaliteit: "goed", toelichting: null },
    { email: "christophedhollande1@orange.fr", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "victor.duponcheele@gmail.com", sales_status: null, sales_rep: null, kwaliteit: "slecht", toelichting: null },
    { email: "km-design@outlook.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "hannahgoens321@gmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "liviuszekely7@gmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "erikvanharck@gmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "stefj.jochems@gmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "stien.vandb@gmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "michael_verleysen@pandora.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "julie.opdebeeck@hotmail.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "stephanie.nackaerts@skynet.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "info@ateliertoo.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "dorien@l-int.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "contact@roijeninterieur.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "charissa_diels@msn.com", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null },
    { email: "Zico.zico@outlook.be", sales_status: null, sales_rep: null, kwaliteit: null, toelichting: null }
  ];

  // Normalize all field values
  const updates: LeadUpdate[] = rawUpdates.map(update => ({
    ...update,
    kwaliteit: normalizeKwaliteit(update.kwaliteit),
    sales_status: normalizeSalesStatus(update.sales_status),
    sales_rep: normalizeSalesRep(update.sales_rep),
    sales_comment: (update as any).sales_comment || null
  }));

  try {
    const response = await supabase.functions.invoke('update-leads-from-sheet', {
      body: { updates }
    });

    if (response.error) {
      throw response.error;
    }

    return response.data;
  } catch (error) {
    console.error('Error processing lead updates:', error);
    throw error;
  }
};