// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.51.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List lead form submissions from the 2026 table, optionally filtered by date range, language, lead type or quality.",
  inputSchema: {
    start_date: z.string().optional().describe("ISO date (YYYY-MM-DD) lower bound on created_at."),
    end_date: z.string().optional().describe("ISO date (YYYY-MM-DD) upper bound on created_at."),
    language: z.enum(["nl", "fr"]).optional().describe("Market language of the lead."),
    type: z.string().optional().describe("Lead magnet type, e.g. stalen, lookbook, korting, keukentrends."),
    kwaliteit: z.string().optional().describe("Lead quality label, e.g. Goed, Redelijk, Slecht."),
    limit: z.number().int().min(1).max(200).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, language, type, kwaliteit, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("form_submissions_2026").select(
      "id, created_at, voornaam, achternaam, email, bedrijf, gemeente, language, type, kwaliteit, sales_status, sales_rep, utm_source, utm_medium, utm_campaign, utm_content, utm_term"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (start_date) query = query.gte("created_at", start_date);
    if (end_date) query = query.lte("created_at", `${end_date}T23:59:59`);
    if (language) query = query.eq("language", language);
    if (type) query = query.eq("type", type);
    if (kwaliteit) query = query.eq("kwaliteit", kwaliteit);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/lead-funnel-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.23.8";
var MQL = ["Redelijk", "Goed", "Goed-klant"];
var SQL = ["Goed", "Goed-klant"];
var lead_funnel_summary_default = defineTool2({
  name: "lead_funnel_summary",
  title: "Lead funnel summary",
  description: "Summarise the 2026 lead funnel (Leads \u2192 MQL \u2192 SQL) for a date range, broken down by market and lead type. SQL excludes keukentrends leads.",
  inputSchema: {
    start_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) lower bound on created_at."),
    end_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) upper bound on created_at.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const rows = [];
    const pageSize = 1e3;
    for (let from = 0; ; from += pageSize) {
      let query = supabase.from("form_submissions_2026").select("created_at, language, type, kwaliteit").order("created_at", { ascending: true }).range(from, from + pageSize - 1);
      if (start_date) query = query.gte("created_at", start_date);
      if (end_date) query = query.lte("created_at", `${end_date}T23:59:59`);
      const { data, error } = await query;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      rows.push(...data ?? []);
      if (!data || data.length < pageSize) break;
    }
    const isMql = (r) => MQL.includes(r.kwaliteit ?? "");
    const isSql = (r) => SQL.includes(r.kwaliteit ?? "") && r.type !== "keukentrends";
    const bucket = (list) => ({
      leads: list.length,
      mql: list.filter(isMql).length,
      sql: list.filter(isSql).length
    });
    const byKey = (key) => Object.fromEntries(
      [...new Set(rows.map((r) => r[key] ?? "unknown"))].map((v) => [
        v,
        bucket(rows.filter((r) => (r[key] ?? "unknown") === v))
      ])
    );
    const summary = {
      range: { start_date: start_date ?? null, end_date: end_date ?? null },
      total: bucket(rows),
      by_market: byKey("language"),
      by_type: byKey("type")
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/campaign-spend.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.23.8";
var campaign_spend_default = defineTool3({
  name: "campaign_spend",
  title: "Meta campaign spend",
  description: "Total Meta Ads spend for a date range, broken down by campaign and adset, from the synced meta_performance data.",
  inputSchema: {
    start_date: z3.string().optional().describe("ISO date (YYYY-MM-DD) lower bound on the report date."),
    end_date: z3.string().optional().describe("ISO date (YYYY-MM-DD) upper bound on the report date."),
    campaign_name: z3.string().optional().describe("Filter to a single campaign name (exact match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, campaign_name }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const rows = [];
    const pageSize = 1e3;
    for (let from = 0; ; from += pageSize) {
      let query = supabase.from("meta_performance").select("date, campaign_name, adset_name, spent").order("date", { ascending: true }).range(from, from + pageSize - 1);
      if (start_date) query = query.gte("date", start_date);
      if (end_date) query = query.lte("date", end_date);
      if (campaign_name) query = query.eq("campaign_name", campaign_name);
      const { data, error } = await query;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      rows.push(...data ?? []);
      if (!data || data.length < pageSize) break;
    }
    const sum = (list) => Math.round(list.reduce((acc, r) => acc + Number(r.spent ?? 0), 0) * 100) / 100;
    const group = (key) => Object.fromEntries(
      [...new Set(rows.map((r) => r[key] ?? "unknown"))].map((v) => [
        v,
        sum(rows.filter((r) => (r[key] ?? "unknown") === v))
      ])
    );
    const result = {
      range: { start_date: start_date ?? null, end_date: end_date ?? null },
      total_spend_eur: sum(rows),
      rows: rows.length,
      by_campaign: group("campaign_name"),
      by_adset: group("adset_name")
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/update-lead-qualification.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.23.8";
var update_lead_qualification_default = defineTool4({
  name: "update_lead_qualification",
  title: "Update lead qualification",
  description: "Update the qualification of a 2026 lead: quality label, sales status, sales rep and/or sales comment.",
  inputSchema: {
    lead_id: z4.string().uuid().describe("The id of the lead in form_submissions_2026."),
    kwaliteit: z4.string().optional().describe("Quality label, e.g. Goed, Redelijk, Slecht."),
    sales_status: z4.string().optional().describe("Sales pipeline status."),
    sales_rep: z4.string().optional().describe("Name of the responsible sales rep."),
    sales_comment: z4.string().optional().describe("Free-text sales note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, kwaliteit, sales_status, sales_rep, sales_comment }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const patch = {};
    if (kwaliteit !== void 0) patch.kwaliteit = kwaliteit;
    if (sales_status !== void 0) patch.sales_status = sales_status;
    if (sales_rep !== void 0) patch.sales_rep = sales_rep;
    if (sales_comment !== void 0) patch.sales_comment = sales_comment;
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("form_submissions_2026").update(patch).eq("id", lead_id).select("id, kwaliteit, sales_status, sales_rep, sales_comment");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "No lead updated (not found or not permitted)." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { lead: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zwytwtwnfouazkuyygkm";
var mcp_default = defineMcp({
  name: "covarte-landingspages",
  title: "covarte-landingspages",
  version: "0.1.0",
  instructions: "Tools for the Covarte landing pages and media dashboard. Use `list_leads` to inspect 2026 lead submissions, `lead_funnel_summary` for Leads \u2192 MQL \u2192 SQL totals per market and lead type, `campaign_spend` for Meta Ads spend, and `update_lead_qualification` to set quality or sales fields on a lead.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, lead_funnel_summary_default, campaign_spend_default, update_lead_qualification_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
