-- Update quality to "Redelijk" for specific email addresses
UPDATE form_submissions 
SET kwaliteit = 'Redelijk'
WHERE email IN (
  'info@uni-build.be',
  'sammy.jespers@gmail.com',
  'jodi_cartuyvels@hotmail.com',
  'info@exactinterior.com',
  'samvl26@icloud.com',
  'steven@atelier29.be',
  'info@hd-interiors.be',
  'charlotte.fockedey@gmail.com',
  'info@renovatie-huis.be',
  'cools.johan.temse@gmail.com',
  'styled@outlook.be',
  'info.woodedgedesign@gmail.com',
  'tegellux@proximus.be',
  'desaerjonas@hotmail.be',
  'info@maximedhondt.be',
  'an-peeters@telenet.be',
  'jonas@artifexinterior.be',
  'fl.schelfhout@gmail.com',
  'cbabou1@hotmail.fr',
  'contact@tinerbos.fr',
  'rd-menuiserie@sfr.fr',
  'juliecrmpn@gmail.com',
  'info@guidosse.com',
  'chvanreeth@gmail.com',
  'info@dcmenuiserie.com',
  'marie@bonten.com',
  'contact@andara-agencement.fr',
  'sebastien@piastrella-carrelage.com',
  'bvoneche@gmail.com',
  'ccracing500@gmail.com',
  'nicophanie@aliceadsl.fr',
  'Contact@andara-agencement.fr',
  'jordi.biebaut@outlook.com',
  'info@vlassakarchitects.be',
  'deneefmanon@gmail.com',
  'stijn.detemmerman@hotmail.com'
);