-- Update sales rep to "Dominique" for specific email addresses
UPDATE form_submissions 
SET sales_rep = 'Dominique'
WHERE email IN (
  'atelier43.wood@gmail.com',
  'team@yvebe.be',
  'lepoutre.pauline@gmail.com',
  'minguetdo@gmail.com',
  'jeromeschmitz.architecte@gmail.com',
  'info@cuisines-mailleux.be',
  'lubriceda@hotmail.frl',
  'admin@opusdesign.be',
  'shift.architecture@skynet.be',
  'Venkensabrina@gmail.com',
  'pillonmarco1983@hotmail.com',
  'francoise-gerard@hotmail.com',
  'styled@outlook.be',
  'zaina.b@menuiseriesac.be',
  'cedric.hoffelt@hotmail.com',
  'vincentleclercq1983@gmail.com',
  'philippedebloos@gmail.com',
  'laurent@hep-design.com',
  'scene10@skynet.be',
  'didier.reyns@comobo.be',
  'info@guidosse.com',
  'chvanreeth@gmail.com',
  'info@dcmenuiserie.com',
  'marie@bonten.com',
  'bvoneche@gmail.com',
  'ccracing500@gmail.com',
  'gaetan.ackermans@hotmail.com',
  'leadegobert@gmail.com',
  'brigittepalmiero@gmail.com',
  'cds0659@gmail.com',
  'mohamedaminben@icloud.com',
  'Malika.ben.abid@dovy.be',
  'debrjacky@hotmail.com',
  'shambuyipeter@yahoo.fr',
  'aurianned@hotmail.com'
);