-- Update sales rep to "Michael" for specific email addresses
UPDATE form_submissions 
SET sales_rep = 'Michael'
WHERE email IN (
  'lize.dekeersmaeker@outlook.be',
  'steven@noitzgroup.be',
  'info@maano.be',
  'glenn@construmax.be',
  'philippe@onki.be',
  'gregory@meublis.be',
  'b.b.renovatie@gmail.com',
  'jenno.adriaenssens@icloud.be',
  'info@ateliernerf.be',
  'jos@jedeka.be',
  'interieurwerken@jwconstruct.be',
  'info@schrijnwerken-quidousse.be',
  'info@egsjikinterieur.be',
  'info@gunternijns.be',
  'decat.christophe@outlook.com',
  'kristofma@hotmail.com',
  'info@braeckmansmaatwerk.be',
  'jonas@artifexinterior.be',
  'info@dekeuken-prins.be',
  'sammy.jespers@gmail.com',
  'info@exactinterior.com',
  'fl.schelfhout@gmail.com',
  'businessglolocally@gmail.com',
  'dorothee.decoratie@icloud.com',
  'info@mgmt-bs.be',
  'sita.langenaeken@gmail.com',
  'inge.vanoirbeek@telenet.be',
  'icm.interieur@gmail.com',
  'cuisines@batyhome.be',
  'xammax32@hotmail.com',
  'klaeremans@gmail.com',
  'mounine.hd@gmail.com',
  'vanweertinterieurbouw@telenet.be',
  'info@vlassakarchitects.be',
  'knokke@qsine.be',
  'hello@stephaniamilazzo.be',
  'geoffrey@eventus-interieur.be',
  'wouters.as@telenet.be'
);