INSERT INTO form_submissions_2026 (voornaam, achternaam, bedrijf, email, telefoon, straat, postcode, gemeente, type_bedrijf, type, marketing_optin, language, utm_source, utm_medium, utm_campaign, utm_term, utm_content)
VALUES 
('Alice', 'Devlieger', 'Dentalplus', 'Hilde.maurice@gmail.com', '+32485849482', 'Koning Leopoldlaan 38', '3920', 'Lommel', 'Interieurarchitect', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_scraping_nl'),
('otsoe verdonckt', 'architectuur', 'O.verdonckt architect', 'otsoe.verdonckt@gmail.com', '+32468324896', 'Braamstraat 18', '3471', 'Hoeleden', 'Interieurarchitect', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_leads_nl'),
('Kristof', 'Knockaert', 'Atelier.Knockaert', 'kristof.knockaert@telenet.be', '+32478442878', 'Frankrijklaan 43', '8970', 'Poperinge', 'Keukenbouwer', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'retargeting_engagement_nl'),
('Heidy van', 'Breda', 'Zelfstandig', 'Info@architectvanbreda.be', '+32498852728', 'Collegestraat 35', '2300', 'Turnhout', 'Interieurarchitect', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'retargeting_engagement_nl'),
('Iris', 'Dryepondt', 'Studioirisdryepondt', 'Iris3pondt@yahoo.com', '+32474969476', 'Boat', '8600', 'Diksmuide', 'Interieurarchitect', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_leads_nl'),
('Tony', 'Debaere', 'Modelka', 'info@modelka.be', '+32476339923', 'kleine Waregemsestraat', '8530', 'Harelbeke', 'Keukenbouwer', 'stalen', true, 'nl', 'paidsocial', 'fb', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'retargeting_engagement_nl'),
('Kathy', 'Van de Gaer', 'Van de gaer', 'kathyvandegaer@gmail.com', '+49496333333', 'Bolwerkstraat 58', '2200', 'Herentals', 'Interieurarchitect', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_leads_nl'),
('Johan', 'Cuypers', 'Cuypers interieurbouw', 'johancuypers14@gmail.com', '+32475843674', 'Geneinde 125', '2260', 'Tongerlo', 'Keukenbouwer', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_scraping_nl'),
('Thibault', 'Costermans', 'Thibault costermans maatkasten & interieur', 'thibault.costermans77@gmail.com', '+32497488560', 'Aststraat 46', '3300', 'Tienen', 'Keukenbouwer', 'stalen', true, 'nl', 'paidsocial', 'ig', 'stretch_be_nl_26_02_mofu_leadgen_scaling_nl', '1_image_stalen_body_short', 'lookalike_scraping_nl');