// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwytwtwnfouazkuyygkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eXR3dHduZm91YXprdXl5Z2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTE2NzgsImV4cCI6MjA2NDc4NzY3OH0.A6HNUTlIc3WdvOSp2i0MLjsYPs7MWoCXIMWqkn6CkwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);